### ISSUE TITLE
Create Deco Crash

### ISSUE THREAD

**Issue by CritFlaw** [talrey/CreateDeco#39]
Through a process of binary searching I've found Create Deco on both `1.2.8` and `1.2.9` to crash in single player. Crashes on startup before getting to menu screen.

Mod list - https://pastebin.com/aunnk1tM
Forge - 40.1.73
Minecraft - 1.18.2

Crash log - https://pastebin.com/ttQT9fge

**Comment by Hahahavana** [comment]
The crash is due to the recent Flywheel update, which has caused multiple other addons to stop working with create as well. A temporary fix would be to downgrade your version of create/addons for create until this mod is fixed.

**Comment by Silverseppel** [comment]
I don't know if it's really the flywheel update because Create Deco is the only addon for Create that has problems at startup. I use besides Create Deco also Ars Creo, Create Crafts & Additions, Create Stuff Additions, Create: Alloeyed, Create: Chromatic Return and Litte Contraptions and only Create Deco crashes the client at startup. Most of the other mods have received updates for compatibility with the latest Create version.

**Comment by Hahahavana** [comment]
That's because all of those addons updated in the last couple days (and a handful like Create Stuff Additions just didn't crash). Check the update description for Crafts and Additions and Alloyed.

**Comment by Silverseppel** [comment]
2 days ago:
Create: Alloyed v1.4c
Fixed:
Mod not working on Create 0.5.0d

5 days ago:
Crafts & Additions
Updated to Create 0.5d

**Comment by 4AC11** [comment]
I really hope this can get fixed soon. I keep having to downgrade mods or not update them because this single mod fails to work with the newest create version (most recently supplementaries, whose newest version crashes when loaded with downgraded versions of Create). Considering this is an addon mod, you'd think being compatible with the main mod would be, yknow, the number one priority...

**Comment by Derpford** [comment]
Is the mod author just...not at their computer?

**Comment by drakray** [comment]
Please see https://www.curseforge.com/minecraft/mc-mods/create-deco?comment=128
Please be patient, be courteous, otherwise they might just say "F*** this I'm not paid enough" and just drop it, seeing as they are just not paid to do this ;)

**Comment by CritFlaw** [comment]
Fixed in the the latest release `createdeco-1.2.10-1.18.2`
