### ISSUE TITLE
Fabric Version is broken 1.18.2

### ISSUE THREAD

**Issue by Hahahavana** [talrey/CreateDeco#48]
What the title says. Causes crashes before the game window even opens.

**Comment by Spiderach** [comment]
That's likely because some changes are needed to be compatible with the latest version of Create. The Fabric version of Create: Deco was last updated in May, and as such has fallen behind as Create has updated. The Fabric version of the mod will need updated before it supports the latest version of Create.

**Comment by talrey** [comment]
Fabric updated release is coming soon, keep an eye on the Discord and let me know once it comes out if you're still having issues.
