### ISSUE TITLE
Catwalks have incorrect particle and sound positions

### ISSUE THREAD

**Issue by Defetyre** [talrey/CreateDeco#55]
When running on catwalks, you can't hear your footsteps; however, if you are jumping and running at the same time, you can see the particles, but only when you reach the top of the block. So it seems that they only produce particles and sounds on the level of their railings.

**Comment by talrey** [comment]
Honestly, catwalks have been a bit of a headache in a lot of respects, and we're putting together plans to rework them. The footstep thing is just one of several issues caused by what I tried to wrangle Minecraft's engine into letting us do. I'm not sure there's anything I can actually do to fix this without mixin tampering as things are now.
