### ISSUE TITLE
Update Request to 1.20.1

### ISSUE THREAD

**Issue by VRPioneerPaul** [talrey/CreateDeco#97]
Please update the the addon for create I’d appreciate it being updated to 1.20.1 because all other mods for create have done it as well

**Comment by adaliszk** [comment]
@talrey Since I see work done on the `1.20-multi` branch, is there a checklist somewhere?

I did build it, and while the fabric source had failed, the mod appears to work on a fabric client. It does load but throws many errors on a fabric server and makes all ladders non-functional.

**Comment by quintaneous** [comment]
Is the mod planning to be ported to 1.20?

**Comment by HttpRafa** [comment]
I see that the branch no longer receives updates, is 1.20.1 still planned?

**Comment by talrey** [comment]
Yes.

**Comment by adaliszk** [comment]
Hmm, @talrey, did you forget to push it to https://www.curseforge.com/minecraft/mc-mods/create-deco/files?
I am asking because you closed this ticket; This would indicate that it is shipped somewhere, but the previous issues remain with the 1.20 branch when I try to build it. Should I open new tickets for each problem, or should we track those in one ticket?

**Comment by talrey** [comment]
I closed this ticket because I get asked about 1.20.1 a **lot** and my response will always be "It's coming." Unless you have specific contributions to make to the `1.20-main` branch, please be patient and the update will be announced in Discord when it's ready.
